language: node_js
node_js:
  - "lts/*"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
  yarn: true
before_install:
  - export TZ='Asia/Shanghai'  # 设置时区
install:
  - npm install
script:
  - npm run build
  - npm run test